version: "3"

services:

  emqx1: &emqx-node
    image: "docker.io/emqx/emqx-enterprise:${EMQX_EE_VERSION}"
    environment: &emqx-node-env
      EMQX_NAME: "emqx"
      EMQX_HOST: "node1.emqx.dev"
      EMQX_CLUSTER__DISCOVERY_STRATEGY: "static"
      EMQX_CLUSTER__STATIC__SEEDS: "[emqx@node1.emqx.dev, emqx@node2.emqx.dev]"
      EMQX_CLUSTER__CORE_NODES: "['emqx@node1.emqx.dev', 'emqx@node2.emqx.dev']"
      EMQX_NODE__DB_BACKEND: "rlog"
      EMQX_NODE__DB_ROLE: "core"
      EMQX_NODE__COOKIE: "${EMQX_ERLDIST_COOKIE}"
    ports:
      - "1884-1893:1883"
      - "8884-8893:8883"
      - "8084-8093:8083"
      - "18084-18093:18083"
    volumes:
      - "./etc/redis/tls/:/etc/redis/tls/"
      - "../config/extra.conf:/opt/emqx/etc/emqx-enterprise.conf"
      - "${EMQX_EXTRA_CONFIG_0:-/dev/null}:/opt/emqx/etc/extra-0.conf"
      - "${EMQX_EXTRA_CONFIG_1:-/dev/null}:/opt/emqx/etc/extra-1.conf"
      - "${EMQX_EXTRA_CONFIG_2:-/dev/null}:/opt/emqx/etc/extra-2.conf"
      - "${EMQX_EXTRA_CONFIG_3:-/dev/null}:/opt/emqx/etc/extra-3.conf"
      - "${EMQX_EXTRA_CONFIG_4:-/dev/null}:/opt/emqx/etc/extra-4.conf"
    networks:
      emqx-bridge:
        aliases: [node1.emqx.dev]
    healthcheck:
      test: emqx_ctl status
      interval: 8s
      retries: 5

  emqx2:
    <<: *emqx-node
    environment:
      <<: *emqx-node-env
      EMQX_HOST: "node2.emqx.dev"
    networks:
      emqx-bridge:
        aliases: [node2.emqx.dev]

  emqx3:
    <<: *emqx-node
    environment:
      <<: *emqx-node-env
      EMQX_HOST: "node3.emqx.dev"
      EMQX_NODE__DB_ROLE: "replicant"
    networks:
      emqx-bridge:
        aliases: [node3.emqx.dev]

  emqx4:
    <<: *emqx-node
    environment:
      <<: *emqx-node-env
      EMQX_HOST: "node4.emqx.dev"
      EMQX_NODE__DB_ROLE: "replicant"
    networks:
      emqx-bridge:
        aliases: [node4.emqx.dev]

  emqx5:
    <<: *emqx-node
    environment:
      <<: *emqx-node-env
      EMQX_HOST: "node5.emqx.dev"
      EMQX_NODE__DB_ROLE: "replicant"
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8083:8083"
      - "18083:18083"
    networks:
      emqx-bridge:
        aliases: [node5.emqx.dev]

  emqx-init:
    image: "registry.gitlab.com/gitlab-ci-utils/curl-jq:1.1.0"
    restart: "on-failure"
    depends_on:
      emqx1: {condition: service_healthy}
      emqx2: {condition: service_healthy}
      emqx3: {condition: service_healthy}
      emqx4: {condition: service_healthy}
      emqx5: {condition: service_healthy}
    command:
      - /bin/bash
      - -c
      - |
        curl -sSf 'http://emqx1:18083/api/v5/login' \
          -H 'Authorization: Bearer undefined' \
          -H 'Content-Type: application/json' \
          --data-raw '{"username":"admin","password":"public"}' > login.json
        curl -sSf 'http://emqx1:18083/api/v5/users/admin/change_pwd' \
          -H "Authorization: Bearer $(cat login.json | jq -r .token)" \
          -H 'Content-Type: application/json' \
          --data-raw '{"new_pwd":"${EMQX_ADMIN_PASSWORD}","old_pwd":"public"}'
    networks:
      - emqx-bridge
