version: "3"

services:

  redis:
    image: docker.io/bitnami/redis:${REDIS_TAG}
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_PORT_NUMBER: "${REDIS_PORT_NUMBER}"
      REDIS_TLS_ENABLED: "yes"
      REDIS_TLS_AUTH_CLIENTS: "${REDIS_TLS_AUTH_CLIENTS:-no}"
      REDIS_TLS_PORT_NUMBER: "${REDIS_TLS_PORT_NUMBER}"
      REDIS_TLS_CERT_FILE: "${REDIS_TLS_CERT_FILE}"
      REDIS_TLS_KEY_FILE: "${REDIS_TLS_KEY_FILE}"
      REDIS_TLS_CA_FILE: "${REDIS_TLS_CA_FILE}"
    volumes:
       - ./etc/redis/tls:/etc/redis/tls
    networks:
      emqx-bridge:
        aliases: ["${EMQX_HOSTNAME_REDIS}"]
